<?php
include_once("addComponente.php");
try {
    
    $curl = curl_init();
    curl_setopt_array($curl, array(
        CURLOPT_URL => "http://homologacao.cobrancabancaria.tecnospeed.com.br:8080/api/v1/retornos/",
        CURLOPT_CUSTOMREQUEST => "POST",
        CURLOPT_SSL_VERIFYPEER => 0,
        CURLOPT_SSL_VERIFYHOST => 0,
        CURLOPT_HTTPHEADER => array(
            "cnpj-cedente: $CNPJCedente",
            "cnpj-sh: $cnpjSH",
            "content-type: application/json",
            "token-sh: $hashSH",
        ),
        CURLOPT_POSTFIELDS => "{\"arquivo\": \"NzU2MDAwMDAgICAgICAgICAyMTAyODQzNjgwMDAxODIgICAgICAgICAgICAgICAgICAgIDA0MzcwMDAwMDAwMDAzMTIzMTIwUFJJTlQgTUlESUEgQ09NVU5JQ0HDh0FPIFZJU1VBTFNJQ09PQiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAyMjEwMzIwMTgwODE1MzQwMDAwMDIwODUwMDAwMCAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIA0KNzU2MDAwMTFUMDEgIDA0MyAyMDEwMjg0MzY4MDAwMTgyICAgICAgICAgIDQzNzAwMDAwMDkwNDM3MDAwMDAwMDAwMzEyMzEyMFBSSU5UIE1JRElBIENPTVVOSUNBw4dBTyBWSVNVQUwgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDAwMDAwMDAwMjEwMzIwMTgwMDAwMDAwMCAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIA0KNzU2MDAwMTMwMDAwMVQgMDYwNDM3MDAwMDAwMDAwMzEyMzEyMDAwMDAwMDAyMzcwMTAxMSAgICAgMTIzICAgICAgICAgICAgIDIwMDMyMDE4MDAwMDAwMDAwMDAxMDAwNzQ4MDczNjgwICAgICAgICAgICAgICAgICAgICAgICAgIDA5MjAxNDg1MTAyNDAwMDE2OUFOQSBMVUNJQSBWSUNFTlRFIC0gTUUgICAgICAgICAgICAgICAgICAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwNCAgICAgICAgICAgICAgICAgDQo3NTYwMDAxMzAwMDAyVSAwNjAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDIwMDMyMDE4MjAwMzIwMTggICAgMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA3NTYwMDAwMDAwMDAwMDAwMDAwMDAwMCAgICAgICANCjc1NjAwMDE1ICAgICAgICAgMDAwMDA0MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIA0KNzU2OTk5OTkgICAgICAgICAwMDAwMDEwMDAwMDYwMDAwMDAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgDQo=\"}",
        
        CURLOPT_TIMEOUT => 30,
        CURLOPT_RETURNTRANSFER => true
    ));
    echo CURLOPT_POSTFIELDS;

    $response = curl_exec($curl);
    $err = curl_error($curl);
    curl_close($curl);

    if ($err) {
        echo "cURL Error #:" . $err;
    } else {
        fwrite($file, $text);
        fclose($file);
        echo prettyPrint($response);
    }
} catch (Exception $e) {
    echo $e;
}